config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/login',  to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  get '/inbox', to: 'conversations#index'
  patch '/notifications', to: 'notifications#seen'
  get '/dashboard', to: 'users#show'
  post '/conversations/new', to: 'conversations#new'






  resources :users do
    resources :matches, only: [:index, :edit, :update, :destroy]
    resources :match_bids, only: [:index, :edit, :update, :destroy]
    resources :conversations
  end

  resources :user_activations, only: [:edit]
  resources :sessions, only: [:create, :destroy]
  resources :tables do
    resources :ratings
    resources :matches
  end

  resources :matches do
    resources :match_bids
  end


  resources :matches
  resources :match_bids
  resources :comments do
    resources :votes
    resources :replies
  end

  resources :pictures

  resources :conversations do
    resources :messages
  end

  resources :messages, only: [:create]
  resources :notifications, only: [:update]
  resources :liked_tables, only: [:create, :destroy]






  resources :password_resets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :table, optional: true
  has_many :replies, class_name: 'Comment', foreign_key: 'parent_id'
  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :votes, dependent: :destroy
  has_many :voters, through: :votes

  validates :content, presence: true
  validates :title, presence: true

  scope :best, -> (table){where(table_id: table.id).order('votes_count DESC').first}

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :logged_in_user
  before_action :current_user
  before_action :correct_user, only: [:edit, :destroy, :update]

  def create
    @comment = @current_user.comments.create(comment_params)
  end

  def edit
    @table = @comment.table
  end

  def destroy
    @comment.destroy
  end

  def update
    @comment.update_attributes(comment_params)
  end

  private

  def comment_params
    params.require(:comment).permit(:table_id, :user_id, :content, :title)
  end

  def correct_user
    @comment = @current_user.comments.find_by(id: params[:id])
    redirect_to root_url if @comment.nil?
  end

end

app/helpers/comments_helper.rb
module CommentsHelper

  def best(comments)
    count = 0
    best = comments.first
    comments.each do |comment|
      if comment.votes.count > count && comment.parent.nil?
        count = comment.votes.count
        best = comment
      end
    end
    best
  end

end

app/views/comments/_comment.html.erb
<div class="comment" data-id="<%=comment.id%>">
  <div class="user_info">
    <%=gravatar_for(@current_user, 33) unless @current_user.nil?%>
    <div class='explanation'><%=comment.user.name%></div>
  </div>

  <div class="review clearfix" data-commentid='<%=comment.id%>'>
    <div class='reply'>
      <% unless comment.parent.nil? %>
        reply to: <%=truncate(comment.parent.content, length: 20)%>
      <% end %>
    </div>
    <div class='comment-title'><%=comment.title if comment.parent.nil?%></div>
    <div class='comment-content'><%=comment.content %></div>
    <% if comment.user == @current_user && !@current_user.nil?%>
      <%=link_to image_tag('bin.svg', size:15), comment_path(comment),
         method: :delete, remote: true, class:'btn-signup', title: 'delete'%>
      <%=link_to image_tag('edit.svg', size:15),edit_comment_path(comment),
         remote: true, class: 'btn-signup btn-margin', title: 'edit'%>
    <% elsif %>
      <% if already_voted?(comment) %>
        <%=render partial: 'votes/vote', locals: {comment: comment,
         method: :delete, url: comment_vote_path(vote(comment),comment_id: comment.id),
         css: 'link-secondary'} %>
      <% else %>
        <%=render partial: 'votes/vote', locals: {comment: comment,
          method: :post, url: comment_votes_path(comment_id: comment.id),
          css: 'link-primary'} %>
      <% end %>
      <%=link_to image_tag('reply.svg', size:15),
         new_comment_reply_path(comment_id: comment.id), title: 'reply',remote: true,
         class: 'link-primary btn-signup btn-margin' %>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<h2> Leave a review of the table </h2>
<%=render partial: 'comments/form1', locals: {submit_text: 'Finish my finding',
       comment: Comment.new, method: 'POST', url: comments_path} %>
<%=link_to "Skip", table_path(@table), class:"btn btn-secondary btn-signup
                                                btn-margin" %>

app/views/comments/_form1.html.erb
<%=form_for comment, url: url, method: method,
            html: {class: "comment_form"}, remote: true do |f| %>

  <%=f.hidden_field :table_id, value: @table.id %>

  <%=f.label :title %>
  <%=f.text_field :title, class:"form-field"%>

  <%=f.label :review %>
  <%=f.text_area :content, class: "textarea",
                placeholder: "What do you think of the table?" %>

  <%=f.submit submit_text, class:'btn btn-primary btn-signup'%>
<% end %>

app/views/comments/create.js.erb
(function(){
  $('#error_explanation').remove()
  <% if @comment.new_record? %>
    var errors = "<%=j render 'shared/error_messages', object: @comment %>";
    $('.comment_form').prepend(errors);
    $('html, body').animate({scrollTop: $("#error_explanation").offset().top}, 500)
  <% else %>
    window.location.href = "<%=table_path(@comment.table_id) %>"
  <% end %>
}) ()

app/views/comments/destroy.js.erb
(function(){
  $('[data-id="<%=@comment.id%>"]').fadeOut();
}) ()

app/views/comments/edit.js.erb
(function(){
  $('[data-commentid="<%=@comment.id%>"]')
  .replaceWith("<%=j render partial: 'form1', locals: {submit_text: 'Update', comment: @comment, url: comment_path(@comment), method: 'PATCH'} %>");
  var selectedComment = $("#edit_comment_<%=@comment.id%>");
  $(document).on('click.editComment',function(event){
    if (!$.contains(selectedComment[0], event.target)){
      $(document).off('click.editComment');
      $('[data-id="<%=@comment.id%>"]').replaceWith("<%=j render @comment%>");
    }
  });
}) ()

app/views/comments/update.js.erb
(function(){
  $(document).off('click.editComment');
  $('[data-id="<%=@comment.id%>"]').replaceWith("<%=j render @comment%>");
}) ()