config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/login',  to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  get '/inbox', to: 'conversations#index'
  patch '/notifications', to: 'notifications#seen'
  get '/dashboard', to: 'users#show'
  post '/conversations/new', to: 'conversations#new'






  resources :users do
    resources :matches, only: [:index, :edit, :update, :destroy]
    resources :match_bids, only: [:index, :edit, :update, :destroy]
    resources :conversations
  end

  resources :user_activations, only: [:edit]
  resources :sessions, only: [:create, :destroy]
  resources :tables do
    resources :ratings
    resources :matches
  end

  resources :matches do
    resources :match_bids
  end


  resources :matches
  resources :match_bids
  resources :comments do
    resources :votes
    resources :replies
  end

  resources :pictures

  resources :conversations do
    resources :messages
  end

  resources :messages, only: [:create]
  resources :notifications, only: [:update]
  resources :liked_tables, only: [:create, :destroy]






  resources :password_resets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_carousel-index.html.erb
<% if table.pictures.any? %>
    <div class='carousel-index'>
      <% table.pictures.each do |pic| %>
        <%= link_to table do %>
          <%=image_tag(pic.picture.url(:index))%>
        <% end %>
      <% end %>
    </div>
<% else %>
  <%=link_to table do %>
    <%=image_tag('fallback/index_default.png', class:'default-img')%>
  <% end %>
<% end %>

app/views/shared/_carousel.html.erb
<div class="carousel">
    <%@pictures.each do |pic|%>
      <div>
        <%=image_tag(pic.picture.url(:show),
              class: "table_standard")%>
      </div>
    <% end %>
</div>

<div class="carousel-small">
    <%@pictures.each do |pic| %>
      <div>
        <%=image_tag(pic.picture.url(:slicknav))%>
      </div>
    <% end %>
</div>

app/views/shared/_error.js.erb
var errorKeys = <%=raw @user.errors.keys.map { |e| "user[#{e}]"}%>;
  console.log($(this).attr('name'), console.log(errorKeys));
  if (errorKeys.includes($(this).attr("name"))) {
    $(this).toggleClass(".form-field-invalid");
  };
});

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li class="error"><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <span class='alert alert-<%=type%> flashbar'>
    <%=message %>
    <%=link_to "×", "#", class: 'exit exit-flash link-primary' %>
  </span>
<% end %>

app/views/shared/_my-rating.html.erb
<span class="explanation">(My rating:</span>
<div class="full_rating small_stars">★★★★★
  <div class="real_rating your_rating"
       style="width:<%=number_to_percentage(rating.overal_rating/10*100,
                                precision: 0)%>">
  ★★★★★</div>
</div>
<span class="explanation"><%=number_with_precision(rating.overal_rating,
                                                precision: 1) %>)</span>

app/views/shared/_notifications.html.erb
<%=link_to image_tag('notification.svg', class:'icon-small icon-position'), "#",
                                                  title: 'see notifications'%>
<div class="notification-number" style="<%='display: none' unless
                                has_unseen?(@current_user)%>">
    <%=unseen_count(@current_user) if has_unseen?(@current_user)%>
</div>
<div class='dropdown-menu notification-dropdown'>
  <div class='notification-title'>
    Notifications
  </div>
  <ul class='notification-list'>
    <%=render notifications(@current_user) %>
  </ul>
</div>

app/views/shared/_profile.html.erb
<%=link_to gravatar_for(@current_user, 25), "#" ,title: 'see my profile'%>
<div class='dropdown-menu profile-dropdown'>
  <ul>
    <li><%=link_to 'My profile', user_path(@current_user), class: 'link-gray'%></li>
    <!-- <li><%=link_to 'Settings', "#", class: 'link-gray'%></li> -->
    <li><%=link_to "Log out",logout_path, method: 'delete', class:'link-gray'%></li>
  </ul>
</div>

app/views/shared/_rating-index.html.erb
<%= link_to table do%>
  <div class="full_rating">★★★★★
    <div class="real_rating"
         style="width:<%=number_to_percentage((table.overal_rating/10)*100,
                                       precision: 0)%>">
    ★★★★★</div>
  </div>
  <span class='explanation link-primary'><%=pluralize(table.ratings.count,'rating')%></span>
  <div class="link-gray link-small table-address"><%=table.address%></div>
<% end %>

app/views/shared/_searchbar.html.erb
<%=form_tag(tables_path, method: 'get', class: 'searchbar', enforce_utf8: false) do %>

  <%=text_field_tag :search, params[:search], placeholder: '🔍    Search by address',
                                              class: 'search',
                                              id: 'autocomplete'%>
  <%=submit_tag('submit', class:'btn btn-primary', id:"search-btn")%>

<% end %>

app/views/shared/_show_upload_photo.js.erb
$('.rate_button').remove();
$('.upload_wrap').append("<%=j render 'pictures/upload' %>").fadeIn('slow');
$('html, body').animate({scrollTop: $(".upload_wrap").offset().top}, 1500);
upload_photo();
$('.upload_wrap').on('click', '.pic_button', function(event){
  event.preventDefault();
  if (!$('.photo_preview').children().length) {
    $('.photo_preview').append("<p class='alert alert-danger'>" +
                                "No photos have been uploaded!</p>");
  } else {
    showComment();
  }
});

$('.upload_wrap').on('click', '.btn-skip', function(event){
  event.preventDefault();
  $('.alert').remove();
  showComment();
});

 function showComment(){
   $('#freeze-photo').show();
   $('.btn-skip').remove();
   $('.pic_button').remove();
   $('.comment_wrap').append("<%=j render partial: 'comments/form'%>").fadeIn('slow');
   $('html, body').animate({scrollTop: $(".comment_wrap").offset().top}, 1500);
 }

app/views/shared/_tmpl.html.erb
<script id='template-upload' type='text/x-tmpl'>
<div>
  {%=o.name%}
  <div class="progress">
    <div class="bar" style="width: 0%"></div>
  </div>
</div>
</script>