config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/login',  to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  get '/inbox', to: 'conversations#index'
  patch '/notifications', to: 'notifications#seen'
  get '/dashboard', to: 'users#show'
  post '/conversations/new', to: 'conversations#new'






  resources :users do
    resources :matches, only: [:index, :edit, :update, :destroy]
    resources :match_bids, only: [:index, :edit, :update, :destroy]
    resources :conversations
  end

  resources :user_activations, only: [:edit]
  resources :sessions, only: [:create, :destroy]
  resources :tables do
    resources :ratings
    resources :matches
  end

  resources :matches do
    resources :match_bids
  end


  resources :matches
  resources :match_bids
  resources :comments do
    resources :votes
    resources :replies
  end

  resources :pictures

  resources :conversations do
    resources :messages
  end

  resources :messages, only: [:create]
  resources :notifications, only: [:update]
  resources :liked_tables, only: [:create, :destroy]






  resources :password_resets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/picture.rb
class Picture < ApplicationRecord

  mount_uploader :picture, PicturesUploader
  belongs_to :table

  validates :picture, presence: true
  validate  :picture_size


  private
  # Validates the size of an uploaded picture.
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def create
    @table = Table.find_by(id: params[:pictures][:table_id])
    @picture = @table.pictures.create(picture_params)
  end

  def destroy
    @picture = Picture.find(params[:id]).destroy
    respond_to do |format|
      format.js
    end
  end


  private

  def picture_params
    params.require(:pictures).permit(:picture, :table_id)
  end


  def set_table
    @table = current_user.tables.build
  end

  def add_more_pictures(new_pictures)
    pictures = @tables.pictures
    pictures += new_pictures
    @table.pictures = pictures
  end

end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%=form_for :pictures, url: pictures_path do |f| %>
  <div class="freeze" id="freeze-photo"></div>
    <%=f.file_field :picture, multiple: true,
                              accept: 'image/jpeg, image/gif, image/png',
                              id: "upload_photo",
                              name: "pictures[picture]"%>
    <%=f.hidden_field :table_id, value: @table.id %>
<% end %>

<ul class="photo_preview">
</ul>

app/views/pictures/_picture.html.erb
<li class="frame" id="pic_<%=@picture.id%>"
  style="background-image: url(<%=@picture.picture_url%>)">

  <%=link_to "×", picture_path(@picture), method: :delete, remote: true,
                                          class:"link-primary delete"%>
</li>

app/views/pictures/_popup_form.html.erb
<div class='pop-up-photo pop-up'>
  <div class='login_form popupphoto_form upload_wrap clearfix'>
    <%=link_to "×", table_path(@table), class: "exit link-primary return"%>
    <%=render 'pictures/form' %>
    <%=link_to "Done", table_path(@table),
        class:'btn btn-primary btn-signup'%>
  </div>
</div>

app/views/pictures/_upload.html.erb
<h2> Got some photos of the table? Upload them! </h2>

<%=render 'pictures/form' %>

<%=link_to "Upload and leave a review", "#",
    class:'btn btn-primary btn-signup pic_button'%>
<%=link_to "Skip", "#", class:'btn btn-secondary btn-signup btn-skip btn-margin' %>

app/views/pictures/create.js.erb
(function(){
  $('#error_explanation').remove()
  <% if @picture.new_record? %>
    var errors = "<%=j render 'shared/error_messages', object: @picture %>";
    $('.photo_upload').prepend(errors);
  <% else %>
    $('.photo_preview').append($("<%=j render @picture %>"))
  <% end %>
}) ()

app/views/pictures/destroy.js.erb
(function(){
  $('#error_explanation').remove()
  <% if @picture.destroyed? %>
    $("#pic_<%=@picture.id%>").fadeOut();
  <% else %>
    var errors = "<%=j render 'shared/error_messages', object: @picture %>";
    $('.photo_upload').prepend(errors);
  <% end %>
}) ()