config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/login',  to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  get '/inbox', to: 'conversations#index'
  patch '/notifications', to: 'notifications#seen'
  get '/dashboard', to: 'users#show'
  post '/conversations/new', to: 'conversations#new'






  resources :users do
    resources :matches, only: [:index, :edit, :update, :destroy]
    resources :match_bids, only: [:index, :edit, :update, :destroy]
    resources :conversations
  end

  resources :user_activations, only: [:edit]
  resources :sessions, only: [:create, :destroy]
  resources :tables do
    resources :ratings
    resources :matches
  end

  resources :matches do
    resources :match_bids
  end


  resources :matches
  resources :match_bids
  resources :comments do
    resources :votes
    resources :replies
  end

  resources :pictures

  resources :conversations do
    resources :messages
  end

  resources :messages, only: [:create]
  resources :notifications, only: [:update]
  resources :liked_tables, only: [:create, :destroy]






  resources :password_resets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/match.rb
class Match < ApplicationRecord

  include ShortDate

  attr_readonly :proposer_id, :table_id


  belongs_to :accepter, class_name: "User", optional: true
  belongs_to :proposer, class_name: "User"
  belongs_to :table
  has_many   :match_bids, dependent: :delete_all
  has_many   :bidders, through: :match_bids, source: :bidder
  has_many   :conversations


  before_validation :load_end_time
  before_destroy    :prevent_destroy
  after_destroy     :send_notice_to_bidders


  # validates :start_at, presence: true
  validates :end_at, presence: true
  validates :accepter_id, inclusion: {in: [nil]}, on: :create
  validates :confirmed, inclusion: {in: [false]}, on: :create
  validate  :valid_start_time
  validate  :proposer_bids
  validate  :table_available
  validate  :proposer_available
  validate  :participant_difference, on: :update
  validate  :freeze_time_slot, on: :update
  validate  :accepter_is_a_bidder, on: :update

  scope :this_table, -> (table) {where(table_id: table.id)}

  scope :time_slot, -> (start_at, end_at) { where(start_at: start_at..end_at)}

  scope :confirmed, ->   { where(confirmed: true)}

  scope :proposed, ->    { where(confirmed: false)}

  scope :proposer_me, -> (user) { where(proposer_id: user.id)}

  scope :accepter_me, -> (user) { where(accepter_id: user.id)}

  scope :participant_me, -> (user) {where(accepter_id: user.id).or(where(proposer_id: user.id))}

  scope :proposer_not_me, -> (user) { where.not(proposer_id: user.id)}

  scope :accepter_not_me, -> (user) { where.not(accepter_id: user.id)}

  scope :i_bidded, -> (user) { joins(:match_bids).where(match_bids: { bidder_id: user.id})}




  private

  def valid_start_time
    errors.add(:you, "can't arrange/change match before current time") if
    (start_at < Time.now)
  end

  def participant_difference
    errors.add(:you, "can't accept your own match") if
    (accepter_id == proposer_id)
  end

  def table_available
    matches = Match.where(table_id: table_id).where("start_at < ? AND end_at > ?",
             end_at, start_at)
    unless matches.empty? or (matches.first == self && matches.length == 1)
      errors.add(:table, "not available for this time slot")
    end
  end

  def proposer_available
    matches = Match.where(proposer_id: proposer_id).or(Match.where(
              accepter_id: proposer_id)).where.not(table_id: table_id).where(
              "start_at < ? AND end_at > ?", end_at, start_at)
    unless matches.empty?
      errors.add(:you, "already have other matches proposed or accepted
                                                          for this time slot")
    end
  end

  def proposer_bids
      bids = MatchBid.joins(:match).where(
          "matches.start_at < ? AND matches.end_at > ? AND match_bids.bidder_id =? ",
          end_at, start_at, proposer_id.to_s)
      unless bids.empty?
        errors.add(:you, "have bidded on matches with the same time slot,
                cancel the bids first before you propose a match with the same
                 slot")
      end
  end


  def freeze_time_slot
    unless self.match_bids.empty?
      errors.add(:you, "can not change time slot as bids already exist") if
      (start_at_changed? || end_at_changed?)
    end
  end

  def load_end_time
    self.end_at = start_at + 30.minutes unless start_at.nil?
  end

  def accepter_is_a_bidder
    bid = MatchBid.where(match_id: id).where(valid_bid: true).where(
                                                      bidder_id: accepter_id)
    if ((bid.empty?) && (accepter_id != nil))
      errors.add(:accepter_id, "The accepter didn't bid for this match")
    end
  end

  def prevent_destroy
    if self.start_at <= Time.now
      errors.add(:match, 'is already passed')
      throw :abort
    end
  end

  def send_notice_to_bidders
    if !self.accepter_id.nil?
      conversations = self.conversations.where(sender_id: accepter_id)
    else
      conversations = self.conversations
    end
    conversations.each do |conversation|
      conversation.messages.create(author_id: conversation.receiver.id,
                                   notice: true,
                                   content: conversation.receiver.name +
                                                          ' canceled the match')
    end
  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
    before_action :logged_in_user
    before_action :current_user
    before_action :get_table, only: [:create]
    before_action :correct_user, only: [:destroy]

  def new
    @match = @current_user.proposed_matches.build
  end

  def index
    @table = Table.find_by(id: params[:table_id])
    if request.xhr?
      if !params[:table_id].nil?
        @confirmed_matches = Match.proposer_not_me(@current_user).accepter_not_me(
                            @current_user).this_table(
                            @table).time_slot(params[:start], params[:end]).confirmed

        @mine_confirmed = Match.proposer_me(@current_user).this_table(
                            @table).time_slot(params[:start], params[:end]).confirmed

        @mine_accepted = Match.accepter_me(@current_user).this_table(
                            @table).time_slot(params[:start], params[:end]).confirmed

        @i_bidded_matches = Match.this_table(@table).time_slot(params[:start],
                            params[:end]).i_bidded(@current_user).proposed

        @proposed_matches = Match.proposer_not_me(
                            @current_user).this_table(@table)
                            .time_slot(params[:start], params[:end])
                            .proposed.where.not(id: @i_bidded_matches.collect(&:id))

        @mine_proposed = Match.proposer_me(@current_user).this_table(
                            @table).time_slot(params[:start], params[:end]).proposed

      elsif !params[:user_id].nil?
        @user = User.find_by(id: params[:user_id])
        @mine_confirmed = Match.participant_me(@user)
                              .time_slot(params[:start], params[:end]).confirmed
        @mine_proposed_user = Match.proposer_me(@user)
                            .time_slot(params[:start], params[:end]).proposed
        if @user == @current_user
          @i_bidded_matches = Match.time_slot(params[:start],
                              params[:end]).i_bidded(@current_user).proposed
        end
      end
    end
    respond_to do |format|
      format.html
      format.json
    end
  end

  def show
    @match = Match.find_by(id: params[:id])
  end

  def create
    @match = @current_user.proposed_matches.build(match_params)
    @match.save
  end

  def update
    @match = Match.find_by(id: params[:id])
    @match.update_attributes(match_params)
  end

  def destroy
    @match.destroy
  end


  private

  def match_params
    params.require(:match).permit(:proposer_id, :accepter_id, :table_id,
                                  :confirmed, :start_at, :end_at)
  end

  def get_table
    @table = Table.find(params[:table_id])
  end


  def correct_user
    @match = @current_user.proposed_matches.find_by(id: params[:id])
    redirect_to root_url if @match.nil?
  end

end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%=form_for :match, url: table_matches_path, remote: true do |f| %>
    <%=f.hidden_field :start_at, class: "start_time" %>
    <%=f.hidden_field :end_at, class: "end_time" %>
    <%=f.hidden_field :table_id, value: params[:table_id] %>
    <%=link_to 'Cancel', "#" ,class: "btn btn-secondary btn-margin exit"%>
    <%=f.submit 'Propose match', class:"btn btn-primary " %>
<% end %>

app/views/matches/_legend.html.erb
<div class='legend-wrap'>
  <div>
    <div class='legend'>
      <div class='legend_title legend_lightblue'></div>
      <span class="explanation">Match proposed by others and open for bid</span>
    </div>
    <div class='legend'>
      <div class='legend_title legend_blue'></div>
      <span class="explanation">Match proposed by others and confirmed</span>
    </div>
  </div>

  <div>
    <div class='legend'>
      <div class='legend_title legend_lightgreen'></div>
      <span class="explanation">Match proposed by you and open for bid</span>
    </div>
    <div class='legend'>
      <div class='legend_title legend_green'></div>
      <span class="explanation">Match proposed by you and confirmed</span>
    </div>
  </div>

  <div>
    <div class='legend'>
      <div class='legend_title legend_orange'></div>
      <span class="explanation">Match that you bidded but not yet confirmed</span>
    </div>
    <div class='legend'>
      <div class='legend_title legend_red'></div>
      <span class="explanation">Match that you bidded and accepted as accepter</span>
    </div>
  </div>

  <div class='legend'>
    <div class='legend_title legend_gray'></div>
    <span class="explanation">Match/Proposal already passed</span>
  </div>

</div>

app/views/matches/_matchinfo.html.erb
<div class="matchinfo-wrap">
  <div class='matchinfo'>
    <%=link_to "×", "#calendar", class: "link-primary return close"%>
    <h3> BatMatch </h3>
    <div class='match-detail'>
      <strong> Start at: </strong>
      <%=match.start_at.to_formatted_s(:long)  %>
    </div>
    <div class='match-detail'>
      <strong> Duration: </strong> 30 mins
    </div>
    <div class='match-detail'>
      <strong> Address: </strong>
      <%=link_to "#{match.table.address}", table_path(match.table_id),
         class:"link-primary" %>
    </div>
    <div class='match-detail'>
      <strong>Proposer:</strong>
      <%=link_to "#{match.proposer.name}", user_path(
                                      match.proposer_id),class: "link-primary"%>
    </div>
      <div class='match-detail'>
        <% if (!match.accepter_id.nil?) %>
          <strong>Accepter:</strong>
          <%=link_to "#{match.accepter.name}", user_path(match.accepter_id),
                                               class:"link-primary" %>
          <% if (match.proposer_id == @current_user.id) && (match.start_at > Time.now) %>
            <%=render partial: 'match_bids/update_form',
                      locals: {bidder: match.accepter, change: false, match_id: match.id,
                               var: true, action: 'Change accepter'}%>
            <%=link_to image_tag('bin.svg', class:"icon-small icon-bin"),
                              match_path(match), method: :delete, remote: true%>
          <% end %>
        <% else %>
          <strong>Bidders:</strong>
          <% if match.bidders.empty? %>
            <span>No bids yet</span>
            <% if match.proposer_id == @current_user.id %>
              <%=link_to image_tag('bin.svg', class:"icon-small icon-bin"),
                              match_path(match), method: :delete, remote: true%>
            <% end %>                  
          <% else %>
            <% match.bidders.each do |bidder| %>
              <div class='bidder'>
                <%=link_to "#{bidder.name}", user_path(bidder),
                    class: "link-primary bidder"%>
                <%if (match.proposer_id == @current_user.id) && (match.start_at > Time.now)%>
                  <%=link_to(image_tag('message.svg',class:"icon-small icon-position"),
                    conversation_messages_path(get_bid(match, bidder).conversation)) %>
                  <%=render partial: 'match_bids/update_form',
                            locals: {bidder: bidder, change: true, match_id: match.id,
                                     var: true, action: 'Accept'}%>
                  <%=link_to image_tag('bin.svg', class:"icon-small icon-bin"),
                     match_path(match), method: :delete, remote: true%>
                <% end %>
              </div>
             <% end %>
           <% end %>
           <div class='clearfix'>
             <% if match.start_at > Time.now %>
              <% if (match.proposer_id != @current_user.id) &&
                                                    (already_bidded?(match))%>
                <%=link_to 'drop bid', match_match_bid_path(params[:id],
                          get_bid(match, @current_user)),method: :delete,
                          remote: true, class: 'btn btn-secondary btn-signup'%>
              <% elsif (match.proposer_id != @current_user.id) &&
                                                    (!already_bidded?(match))%>
                <%=render 'match_bids/new_form'%>
              <% end %>
             <% end %>
           </div>
         <% end %>
      </div>
  </div>
</div>

app/views/matches/_render_event.js.erb
$('.calendar').fullCalendar(
   'renderEvent',
   $.parseJSON(
     "<%=j render(partial: match, locals: {color: 'lightgreen', edit: true},format: :json).html_safe %>"),
   false
 );

app/views/matches/create.js.erb
(function(){
  $('.pop-up-photo').hide();
  $('#error_explanation').remove()
  <% if @match.new_record? %>
    var errors = "<%=j render 'shared/error_messages', object: @match %>";
    $('.calendar').prepend(errors);
    $('html, body').animate({scrollTop: $("#error_explanation").offset().top}, 500)
  <% else %>
    <%=render partial: 'matches/render_event.js.erb', locals: {match: @match}%>
  <% end %>
}) ()

app/views/matches/destroy.js.erb
$('.calendar').fullCalendar('removeEvents', [<%=@match.id %>]);
$('.matchinfo-wrap').remove();

app/views/matches/index.html.erb
<div class="content">
  <h1>Propose a BatMatch! </h1>
  <p> You can propose a BatMatch by clicking on the calendar below.
      Each match lasts 30 minutes. If you want to play for longer,
      you can propose multiple matches in a row. </p>
  <p>  Once your proposal is up,
          people can start bidding for it. It's then up to you to
          choose your rival.  </p>
  <p> You can also change the proposal by dragging it directly on the calendar
      when nobody hasn't bidded on the match. Once the first bid appears, you can
      no longer change the proposal. </p>
  <p class="strong"> Propose a match now to start
      having fun!</p>
  <div class="table_info">
    <div class="left-part calendar" id="calendar" data-tableid="<%=@table.id%>">
      <div id="calendarBin"><%=image_tag('bin.svg', class:"icon-small icon-position")%></div>
      <div class='pop-up-photo pop-up'>
        <div class='login_form popupphoto_form'>
          <p>Confirm the proposal?</p>
            <%=render 'form' %>
          </div>
        </div>
      <%=render 'legend' %>
    </div>

    <div class="right-part photo-calendar">
      <%=render partial: 'shared/carousel-index', locals: {table: @table} %>
      <%=render 'tables/facility' %>
    </div>
  </div>
</div>

app/views/matches/new.js.erb
$('.pop-up-photo').fadeIn();

app/views/matches/show.js.erb
$('.matchinfo-wrap').remove()
$('.calendar').append("<%=j render partial: 'matchinfo', locals: {match: @match} %>")

app/views/matches/update.js.erb
(function(){
  $('#error_explanation').remove()
  $('.calendar').fullCalendar('removeEvents', [<%=@match.id %>])
  <% if @match.errors.any? %>
    var errors = "<%=j render 'shared/error_messages', object: @match %>";
    $('.calendar').prepend(errors);
    $('html, body').animate({scrollTop: $("#error_explanation").offset().top}, 500);
    <%=render partial: 'matches/render_event.js.erb', locals: {match: @match.reload} %>
  <% else %>
    <%=render partial: 'matches/render_event.js.erb', locals: {match: @match} %>
  <% end %>
}) ()